AWSTemplateFormatVersion: '2010-09-09'
Description: S3 to Lambda event-based trigger to copy object to another bucket

Resources:

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-source"

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-destination"
